
#' Bayesian Models for Age Estimation with Priors from Model_DC14 Dataset
#'
#' @param **(required)** [list] of objects :
#' - Vector of Equivalent doses and C14 Calibrated Ages in the right order according to stratigraphy
#' - dose rates : `ddot`
#' - standard error for D : `sD`
#' - Error of the C14 Calibrated age : `SigmaC14Cal`
#' - Error of the Gaussian distribution UTh : `sigma_UTh`
#' @param Nb_sample [integer] number of samples
#' @param SampleNames [character] character vector with sample names
#' @param encoding [vector] encoder, 2 for UTh,  1 if OSL and 0 if C14
#' @param ThetaMatrix [matrix] or [character] input of systematic and individual errors.
#' @param prior [character] : Character string specifying the name of one of the models
#'   available in the `Model_DC14` dataset. Use [extract_Jags_model()] to see all available options
#' @param model [character] (optional) custom Jags model
#' @param StratiConstraints [matrix] or [character] The stratigraphic relation between samples
#' @param PriorAge  vector (with default): lower and upper bounds for age parameter of each sample (in ka)
#' @param SavePdf [logical] (with default): if TRUE save graphs in pdf file named `OutputFileName` in folder `OutputFilePath`.
#' @param OutputFileName OutputFileName [character] (with default): name of the pdf file that will be generated by the function if `SavePdf = TRUE`;
#' \code{length(OutputFileName)=2}, see \bold{PLOT OUTPUT} in \bold{Value} section for more informations.
#' @param OutputFilePath [character] (with default): path to the pdf file that will be generated by the function if \code{SavePdf}=TRUE.
#' If it is not equal to "", it must be terminated by "/".
#' @param SaveEstimates [logical] (with default): if TRUE save Bayes' estimates, credible interval at level 68% and 95%,
#' the result of the Gelman en Rubin test of convergence and the Time Series SE, in a csv table named \code{OutputFileName} in folder \code{OutputFilePath}.
#' @param OutputTableName [character] (with default): name of the table that will be generated by the function if `SaveEstimates = TRUE`.
#' @param OutputTablePath [character] (with default): path to the table that will be generated by the function if `SaveEstimates = TRUE`.
#' @param monitors [vector] (with default):
#' @param CalibrationCurve [character] (with default): calibration curve chosen, for C-14 samples.
#' @param MCMC_plots [logical] (with default): enable/disable MCMC and ACF plots.
#' @param Iter (with default): the number of iterations to run which will be used to assess convergence and ages (see [runjags::run.jags]).
#' @param burnin  [integer] (with default): the number of iterations used to "home in" on the stationary posterior distribution. These are not used for assessing convergence (see [runjags::run.jags]).
#' @param adapt [integer] (with default): the number of iterations used in the adaptive phase of the simulation (see [runjags::run.jags]).
#' @param t [integer] (with default): 1 every \code{t} iterations of the MCMC is considered for sampling the posterior distribution.
#' (for more information see [runjags::run.jags]).
#' @param n.chains [integer] (with default): number of independent chains for the model (for more information see [runjags::run.jags]).
#' @param jags_method [character] (with default): select which method to use in order to call JAGS. jags_methods `"rjparallel"`  (the default) and `"rjags"` have been tested. (for more information about these possibilities and others, see [runjags::run.jags])
#' @param autorun [logical] (with default): choose to automate JAGS processing. JAGS model will be automatically extended until convergence is reached (for more information see [runjags::autorun.jags]).
#' @param quiet [logical] (with default): enables/disables `rjags` messages
#' @param roundingOfValue [integer] (with default): Integer indicating the number of decimal places to be used
#' @param ...
#'
#' @returns
#' **NUMERICAL OUTPUT**
#'
#'  **A list of type `BayLum.list` containing the following objects:**
#'  \itemize{
#'  \item \bold{Ages} : dataframe containing the Credible interval at 95% and 68%, the bayes mean estimator, the bayes standard deviation estimator and sample names.
#'   \item \bold{Sampling}: that corresponds to a sample of the posterior distributions
#'  of the age (in ka);
#'   \item \bold{prior}: category of prior used. `prior == unconstrained` if no stratigraphic constraints;
#'   \item \bold{PriorAge}: stating the priors used for the age parameter (in ka);
#'   \item \bold{StratiConstraints}: stating the stratigraphic relations between samples considered in the model;
#'   \item \bold{CovarianceMatrix}: stating the covariance matrix of error used in the model, highlighting common errors between samples or not;
#'   \item \bold{model}: returns the model that was used for the Bayesian modelling as a [character];
#'   \item \bold{diagnostics_plots}: List of MCMC and ACF plots for the diagnostics of convergence -- check attributes for Gelman CV;
#'   \item \bold{Summary}: Summary Table of the posterior's MCMC;
#'  }
#' @export
#'
#' @examples
#' \dontrun{
#'  D = c(17.72383, 104.95460 )
#'sD = c(0.6, 4)
#'M = c(D[1], DATA_C14$C14[1,1], D[2]) # measures
#' DATA3 <- combine_DataFiles(L1 = DATA2, L2 = DATA1)
#' Nb_sample = 3
#' SampleNames = c("GDB5", DATA_C14$Names[1], "GDB3")
#' Theta = diag(c(DATA3$ddot_env[1,1]**2 * .1, DATA3$ddot_env[1,2]**2 * .1))
#' encoding = c(1,0,1)
#' ## DATA input
#' dt = list(M = M, sD = sD, ddot = DATA3$ddot_env[1,], sigmaC14Cal =  DATA_C14$C14[1,2])
#'
#'
#' Compute_AgeS_DC14(dt, Nb_sample, SampleNames, encoding, Theta,
#' prior = "Unconstrained"))
#'
#'
#' }
Compute_AgeS_DC14 <- function(
    DATA, #Data_C14Cal, Data_SigmaC14Cal
    Nb_sample ,
    SampleNames,
    encoding,
    ThetaMatrix = c(),
    prior = "Unconstrained",
    model = NULL,
    StratiConstraints = c(),
    PriorAge = rep(c(1, 60), Nb_sample),
    SavePdf = FALSE,
    OutputFileName = c('MCMCplot', 'HPD_Cal14CCurve', "summary"),
    OutputFilePath = c(""),
    SaveEstimates = FALSE,
    OutputTableName = c("DATA"),
    OutputTablePath = c(''),
    monitors = c("A"),
    CalibrationCurve = c("IntCal20"),
    MCMC_plots = F,
    Iter = 10000,
    burnin = 4000,
    adapt = 1000,
    t = 5,
    n.chains = 3,
    jags_method = "rjparallel",
    autorun = FALSE,
    quiet = FALSE,
    roundingOfValue = 3,
    ...
) {

  #
  index_osl = which(encoding == 1)
  index_c14 = which(encoding == 0)
  index_uth = which(encoding == 2)

  n_uth = length(index_uth)
  n_osl = length(index_osl)
  n_c14 = length(index_c14)

  has_osl = n_osl >0
  has_uth = n_uth >0
  has_c14 = n_c14>0

  n_types = sum(has_uth, has_c14, has_osl)

  #OSL settings
  if (has_osl) {
  ## sigma_D For Equivalent doses D when mixing
  encode_sD = rep(0, Nb_sample)
  encode_sD[encoding ==1] = DATA$sD**2
  order_osl = 1:n_osl
  CS_osl = cumsum(encoding == 1)
  # grid = expand.grid(index_osl, index_osl)
  Theta_Tilde = matrix(0, Nb_sample, Nb_sample)
  Theta_Tilde[index_osl, index_osl] = ThetaMatrix
  }

  ## C14 settings
  if (has_c14) {
  order_c14 = 1:n_c14
  CS_c14 = cumsum(encoding == 0)

  #--- Calibration curve ####
  TableauCalib = c()
  if (CalibrationCurve %in%  c(
    "IntCal13", "IntCal20", "Marine13", "Marine20", "SHCal13" , "SHCal20")) {
    TableauCalib = get(data(list = CalibrationCurve, envir = environment()))
  } else {
    TableauCalib = read.csv(file = CalibrationCurve,
                            sep = ",",
                            dec = ".")
  }

  if (startsWith(CalibrationCurve, "SH")) {
    AgeBP = TableauCalib[, 1]
    CalC14 = TableauCalib[, 2]
    SigmaCalC14 = TableauCalib[, 3]
  }
  else {

    AgeBP = rev(TableauCalib[, 1])
    CalC14 = rev(TableauCalib[, 2])
    SigmaCalC14 = rev(TableauCalib[, 3])
  }

  }


  if (has_uth) {
  order_uth = 1:n_uth
  CS_uth = cumsum(encoding == 2)
  }








  if (prior == "Constrained" || prior == "NichollsJones") {

    dataList = list(
      "I" = Nb_sample,
      "Theta" = Theta_Tilde,
      "encoded_covD" = diag(encode_sD),
      "ddot" = DATA$ddot,
      "xbound" = PriorAge,
      "M" = DATA$M,
      "sigma" = DATA$sigmaC14Cal,
      "order_osl" = order_osl,
      "order_c14" = order_c14,
      "index_osl" = index_osl,
      "index_c14" = index_c14,
      "xTableauCalib" = AgeBP,
      "yTableauCalib" = CalC14,
      "zTableauCalib" = SigmaCalC14
    )
  }


  else if ( startsWith(prior, "Unconstrained") ) {

  if (n_types == 3) {

    prior <- "Unconstrained_OSL_C14_UTh"
          dataList = list(
          "Theta" = Theta_Tilde,
          "encoded_covD" = diag(encode_sD),
          "ddot" = DATA$ddot,
          "xbound" = PriorAge,
          "M" = DATA$M,
          "sigma" = DATA$sigmaC14Cal,
          "sigma_uth" = DATA$sigma_UTh,
          "order_osl" = order_osl,
          "order_c14" = order_c14,
          "order_uth" = order_uth,
          "index_osl" = index_osl,
          "index_c14" = index_c14,
          "index_uth" = index_uth,
          "xTableauCalib" = AgeBP,
          "yTableauCalib" = CalC14,
          "zTableauCalib" = SigmaCalC14
        )
  }
    else if (has_osl & has_c14) {

      prior <- "Unconstrained_OSL_C14"

      dataList = list(
        "Theta" = Theta_Tilde,
        "encoded_covD" = diag(encode_sD),
        "ddot" = DATA$ddot,
        "xbound" = PriorAge,
        "M" = DATA$M,
        "sigma" = DATA$sigmaC14Cal,
        "order_osl" = order_osl,
        "order_c14" = order_c14,
        "index_osl" = index_osl,
        "index_c14" = index_c14,
        "xTableauCalib" = AgeBP,
        "yTableauCalib" = CalC14,
        "zTableauCalib" = SigmaCalC14
      )
    }

    else if (has_osl & has_uth) {

      prior <- "Unconstrained_OSL_UTh"

      dataList = list(
        "Theta" = Theta_Tilde,
        "encoded_covD" = diag(encode_sD),
        "ddot" = DATA$ddot,
        "xbound" = PriorAge,
        "M" = DATA$M,
        "sigma_uth" = DATA$sigma_UTh,
        "order_osl" = order_osl,
        "order_uth" = order_uth,
        "index_osl" = index_osl,
        "index_uth" = index_uth
      )
    }

    else if (has_uth & has_c14) {

      prior <- "Unconstrained_C14_UTh"

      dataList = list(
        "xbound" = PriorAge,
        "M" = DATA$M,
        "sigma" = DATA$sigmaC14Cal,
        "sigma_uth" = DATA$sigma_UTh,
        "order_c14" = order_c14,
        "order_uth" = order_uth,
        "index_c14" = index_c14,
        "index_uth" = index_uth,
        "xTableauCalib" = AgeBP,
        "yTableauCalib" = CalC14,
        "zTableauCalib" = SigmaCalC14
      )
    }
  }

  print(prior)
    Model_DC14 <- 0
    data(Model_DC14, envir = environment())
    if (is.null(model)) {
      entry_model = model
      model <- Model_DC14[[prior]]
    }

    #
    if (!(autorun)) {
      #write model in tempfile
      temp_file <- tempfile(fileext = ".txt")
      writeLines(model, con = temp_file)
      if ( startsWith(prior, "Unconstrained") ) {

        inits = replicate(n.chains, list(u = runif(Nb_sample)), simplify = F)
      }

      else if (  prior == "Constrained") {

        inits = replicate(n.chains, list( e = rexp(Nb_sample + 1)), simplify = F)
      }

      else if (prior == "NichollsJones") {    ######

        inits = replicate(n.chains, nichollsInit(Nb_sample, 1, 0), simplify = F)

      }

      results_runjags <- suppressWarnings(runjags::run.JAGS(
        model = temp_file,
        data = dataList,
        n.chains = n.chains,
        monitor = monitors,
        adapt = adapt,
        burnin = burnin,
        sample = Iter,
        silent.jags = quiet,
        method = jags_method,
        thin = t,
        inits = inits
      )
    )# Silence known harmless rjags warnings caused by non-UTF8 Windows locales (e.g. French Windows)

    }

      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
      # JAGS RUN --------------------- END
      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

      #---processing of JAGS results
      ##extract mcmc list from runjags object
      echantillon <- results_runjags$mcmc
      SummaryMCMC <- summary(echantillon)

      ##combine all of them
      sample = as.data.frame(runjags::combine.mcmc(echantillon))

      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
      #                           START OF MCMC'S DIAGNOSIS
      # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

      diagnostics_plots = create_diagnostic_plots(echantillon, SampleNames)
      CV <- gelman.diag(echantillon, multivariate = FALSE)
      cat(paste(
        "\n\n>> Results of the Gelman and Rubin criterion of convergence <<\n"
      ))
      print(CV)

      #optional display for plots
      if (MCMC_plots) {
        display_diagnostic_plots(diagnostic_plots)
      }

      if (SavePdf) {
        pdf_path = paste0(OutputFilePath, OutputTableName[1], ".pdf")
        save_diagnostic_plots(diagnostic_plots, pdf_path)
      }

      cat(
        "\n\n---------------------------------------------------------------------------------------------------\n"
      )
      cat(
        " *** WARNING: The following information are only valid if the MCMC chains have converged  ***\n"
      )
      cat(
        "---------------------------------------------------------------------------------------------------\n\n"
      )
      #---print results ####
      ##Matrix of results
      rnames <- paste0("A_", SampleNames)

      R <- matrix(
        data = NA,
        ncol = 10,
        nrow = Nb_sample,
        dimnames = list(rnames,
                        c(
                          "lower bound at 95%",
                          "lower bound at 68%",
                          "Bayes estimate",
                          "upper bound at 68%",
                          "upper bound at 95%",
                          "Bayes sd",
                          "Convergencies: Point estimate",
                          "Convergencies: uppers confidence interval",
                          "Time Series SE",
                          "Geweke Criteria pvalue"
                        )
        )
      )


      #Bayes Estimate and credibal iterval
      cat(
        "\n\n>> Bayes estimates of Age, Palaeodose and its dispersion for each sample and credible interval <<\n"
      )

      credible95 <-  apply(sample, 2, CredibleInterval, level = .95)[ 1:2, ]
      credible68 <- apply(sample, 2, CredibleInterval, level = .68)[1:2, ]
      estimate <- apply(sample, 2, mean)
      standardError <- apply(sample, 2, sd)
      geweke = geweke.diag(as.mcmc(sample))$z
      pvalue = 2*apply(rbind(pnorm(geweke), pnorm(geweke, lower.tail = F)), 2, min)

      R[, c(1,5)] <- round(t(credible95), roundingOfValue)
      R[, c(2,4)] <- round(t(credible68), roundingOfValue)
      R[, 3] <-   round(estimate, roundingOfValue)

      R[, c(7, 8)] <- round(CV$psrf, roundingOfValue)
      R[, 6] <- round(standardError, roundingOfValue)
      R[, 9] <- round(SummaryMCMC$statistics[, 4], roundingOfValue)
      R[, 10] <- pvalue

      R <- dplyr::as_tibble(R)
      R <- R %>% dplyr::mutate(GewekeStars = stratify_pvalue(pvalue))


      print(data.frame(R) )
      cat("\n----------------------------------------------\n")

      #---print csv table ####
      if (SaveEstimates == TRUE) {
        write.csv(R, file = c(
          paste(
            OutputTablePath,
            "Estimates",
            OutputTableName,
            ".csv",
            sep = ""
          )
        ))
      }

      #---Create return object ####
      .list_BayLum <- function(..., originator = sys.call(which = -1)[[1]]){
        ## set list
        l <- list(...)

        ## update originators
        attr(l, "class") <- "BayLum.list"
        attr(l, "originator") <- as.character(originator)

        return(l)

      }

      output <- .list_BayLum(
        "Ages" = data.frame(
          SAMPLE = SampleNames,
          AGE = estimate,
          SD = standardError,
          HPD68.MIN = credible68[ 1,],
          HPD68.MAX = credible68[2, ],
          HPD95.MIN = credible95[1, ],
          HPD95.MAX = credible95[2, ],
          stringsAsFactors = FALSE
        ),
        "Sampling" = echantillon,
        # "prior" = if(is.null(entry_model)) prior else NaN,
        "PriorAge" = PriorAge,
        "prior" = if(is.null(entry_model)) prior else NaN,
        "StratiConstraints" = StratiConstraints,
        "CovarianceMatrix" = if (has_osl) Theta_Tilde else NULL,
        "model" = model,
        "diagnostics_plots" = diagnostics_plots,
        # "runjags_object" = results_runjags,
        "Summary" = R
      )


      #---Plot ages ####
      plot_Ages(object = output, legend.pos = "bottomleft", model = paste("BayLum", prior), plot_mode = "density")

      return(output)

}
